#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("MoreMobileController.Android.Resource", IsApplication=true)]

namespace MoreMobileController.Android
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Animator
		{
			
			// aapt resource value: 0x7f050000
			public const int control_button = 2131034112;
			
			static Animator()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Animator()
			{
			}
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int arrowDown = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int arrowLeft = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int arrowRight = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int arrowUp = 2130837507;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f080007
			public const int backwardButton = 2131230727;
			
			// aapt resource value: 0x7f080004
			public const int connectButton = 2131230724;
			
			// aapt resource value: 0x7f08000b
			public const int forwardButton = 2131230731;
			
			// aapt resource value: 0x7f080000
			public const int hostEditText = 2131230720;
			
			// aapt resource value: 0x7f080009
			public const int leftButton = 2131230729;
			
			// aapt resource value: 0x7f080001
			public const int linearLayout1 = 2131230721;
			
			// aapt resource value: 0x7f080008
			public const int modeButton = 2131230728;
			
			// aapt resource value: 0x7f080003
			public const int portEditText = 2131230723;
			
			// aapt resource value: 0x7f080006
			public const int relativeLayout1 = 2131230726;
			
			// aapt resource value: 0x7f08000a
			public const int rightButton = 2131230730;
			
			// aapt resource value: 0x7f080002
			public const int space1 = 2131230722;
			
			// aapt resource value: 0x7f080005
			public const int statusTextView = 2131230725;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f040000
			public const int Connect = 2130968576;
			
			// aapt resource value: 0x7f040001
			public const int Control = 2130968577;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class Mipmap
		{
			
			// aapt resource value: 0x7f030000
			public const int Icon = 2130903040;
			
			static Mipmap()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Mipmap()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f060001
			public const int app_name = 2131099649;
			
			// aapt resource value: 0x7f060000
			public const int hello = 2131099648;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7f070000
			public const int blue_button = 2131165184;
			
			static Style()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Style()
			{
			}
		}
	}
}
#pragma warning restore 1591
